FROM node:18-alpine

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG SUPABASE_JWT_SECRET
ENV SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}

ARG TMDB_API_READ_ACCESS_TOKEN
ENV TMDB_API_READ_ACCESS_TOKEN=${TMDB_API_READ_ACCESS_TOKEN}

ENV WORKDIR /castle-app/
WORKDIR $WORKDIR
RUN mkdir -p $WORKDIR
COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .
RUN yarn install --frozen-lockfile
COPY src/ src/
RUN yarn tsc
EXPOSE 8080
CMD node ./dist/src/application/index.js